version: '4.5'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    env_file:
      - .env
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
